on: push

jobs:
  build:
    runs-on: windows-2025-vs2026
    steps:
      - uses: actions/checkout@v6
      - run: ./build.ps1
      - uses: softprops/action-gh-release@v3
        if: github.ref_type == 'tag'
        with:
          draft: true
          files: Build/Release/Installer/*.msi.zip
      - uses: actions/upload-artifact@v7
        with:
          name: Build artifacts
          path: Build/Release/Installer/*.msi.zip
